---
- name: Update apt
  apt: update_cache=yes

- name: Install required tools
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Update apt
  apt: update_cache=yes

- name: Install required tools
  apt: name=docker-ce=17.03.2~ce-0~ubuntu-xenial

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes